version = "1.45.0"

[targets.aarch64-macos]
url = "https://github.com/casey/just/releases/download/1.45.0/just-1.45.0-aarch64-apple-darwin.tar.gz"
bin = "just"
sha256 = "5bcffd1e4b2b24f71a2acff52a604e9da03615679c0b3045a8c921c95cf1532c"

[targets.x86_64-linux]
url = "https://github.com/casey/just/releases/download/1.45.0/just-1.45.0-x86_64-unknown-linux-musl.tar.gz"
bin = "just"
sha256 = "dc3f958aaf8c6506dd90426e9b03f86dd15e74a6467ee0e54929f750af3d9e49"
