version = "0.12.3"

[targets.aarch64-macos]
url = "https://github.com/ClementTsang/bottom/releases/download/0.12.3/bottom_aarch64-apple-darwin.tar.gz"
bin = "btm"
sha256 = "106e9493d20192d18dbe46d4c99f680d817c796724103ee258567070fcd16429"

[targets.x86_64-linux]
url = "https://github.com/ClementTsang/bottom/releases/download/0.12.3/bottom_x86_64-unknown-linux-musl.tar.gz"
bin = "btm"
sha256 = "0d6352079422fda8f4ee242eb849f45a6008db96d6c1cd35e8436babc51bc33f"

[targets.x86_64-macos]
url = "https://github.com/ClementTsang/bottom/releases/download/0.12.3/bottom_x86_64-apple-darwin.tar.gz"
bin = "btm"
sha256 = "5744b5c78db14b85e025c31ded93ba038041e6ff2e8c16ea1d2f9bdb6487316f"
