version = "0.67.0"
description = "A command-line fuzzy finder"

[targets.aarch64-macos]
url = "https://github.com/junegunn/fzf/releases/download/v0.67.0/fzf-0.67.0-darwin_arm64.tar.gz"
bin = "fzf"
sha256 = "b7f34c964d8e52c471c933cef8ec43dc71997c266cafafd1b013bed10fc229a1"

[targets.x86_64-linux]
url = "https://github.com/junegunn/fzf/releases/download/v0.67.0/fzf-0.67.0-linux_amd64.tar.gz"
bin = "fzf"
sha256 = "4be08018ca37b32518c608741933ea335a406de3558242b60619e98f25be2be1"

[targets.x86_64-macos]
url = "https://github.com/junegunn/fzf/releases/download/v0.67.0/fzf-0.67.0-darwin_amd64.tar.gz"
bin = "fzf"
sha256 = "88dc853e0914793a2e7be0d1acfe6c922d9ccad08e3302df092399775b0279ff"
