version = "0.56.3"
description = "A command-line fuzzy finder"

[targets.x86_64-linux]
url = "https://github.com/junegunn/fzf/releases/download/v0.56.3/fzf-0.56.3-linux_amd64.tar.gz"
bin = "fzf"
sha256 = "78e96a88cecfbdb3ff65df89cc47c02573407aee0edd08c87e18a8033d498fef"

[targets.aarch64-macos]
url = "https://github.com/junegunn/fzf/releases/download/v0.56.3/fzf-0.56.3-darwin_arm64.tar.gz"
bin = "fzf"
sha256 = "e626056343fd6814a13ab28b8530f771b80dca7c8393c56b82df4229a7424d63"
