version = "15.1.0"
description = "Recursively searches directories for a regex pattern"

[targets.aarch64-macos]
url = "https://github.com/BurntSushi/ripgrep/releases/download/15.1.0/ripgrep-15.1.0-aarch64-apple-darwin.tar.gz"
bin = "rg"
sha256 = "378e973289176ca0c6054054ee7f631a065874a352bf43f0fa60ef079b6ba715"

[targets.x86_64-linux]
url = "https://github.com/BurntSushi/ripgrep/releases/download/15.1.0/ripgrep-15.1.0-x86_64-unknown-linux-musl.tar.gz"
bin = "rg"
sha256 = "1c9297be4a084eea7ecaedf93eb03d058d6faae29bbc57ecdaf5063921491599"

[targets.x86_64-macos]
url = "https://github.com/BurntSushi/ripgrep/releases/download/15.1.0/ripgrep-15.1.0-x86_64-apple-darwin.tar.gz"
bin = "rg"
sha256 = "64811cb24e77cac3057d6c40b63ac9becf9082eedd54ca411b475b755d334882"
